### PR TITLE
Update index.markdown: misconception &#x1F6AB;

### PR DESCRIPTION
**Pull request by GregTonoski**

### CODE REVIEW

**Comment by Retropex** [comment]
I prefer to keep a rather serious style.

**Comment by GregTonoski** [comment]
I'm insisting on adding a symbol indicating misconception (e.g. 0x1F6AB or 0x1F53B). Otherwise, the sole subtitles look like endorsement of the misconceptions at first sight.

**Comment by Retropex** [comment]
@piratebiscuit your opinion ?

**Comment by piratebiscuit** [comment]
I'm against this change, let's keep the page serious. I do not believe that this change would help someone who's trying to make a decision better judge the situation. It can also be seen as childish and doesn't bring much. 
Let's present things and arguments as they are and let users decide by themselves if this is 💩 or 🤩.

NACK for me, but I would welcome and support future changes that would help better present the situation.

**Pull request closed without merging**
