### PR TITLE
Tentative to solve the Dune iframe non-responsiveness issue

### PR DESCRIPTION
**Pull request by piratebiscuit**
Trying to solve #19 , requesting review from @Retropex .
Is this the right way to do it?

### CODE REVIEW

**Review by Retropex — COMMENTED** [review]
Is not currently working.

~~see~~ [~~dev page~~](https://retropex.github.io/wtfhappenedinfeb2023/)

**Comment by piratebiscuit** [comment]
It works locally, just double checked... Needs more investigation.
À suivre.

**Review by Retropex — APPROVED** [review]
The problem should be solved with the commit https://github.com/wtfhappenedinfeb2023/wtfhappenedinfeb2023.github.io/pull/20/commits/e77d72acdad8acc2838ca6055b16ebf1e317bc6a

**Comment by piratebiscuit** [comment]
Amazing! It was that simple...
Thanks @Retropex, let's merge!

**Pull request merged**
